Repository Lotte-Feelmycode/the-parabole-fe, pull requests merged in 2022-11, with the labels that each got.

#92 [Feature/cartMain] 장바구니 쿠폰목록 적용
  components/cart/CartContent.js
  components/cart/CartContentDetail.js
  components/cart/CartContentFooter.js
  components/cart/CartContentHeader.js
  components/cart/CartCouponModal.js
  components/cart/CartFooter.js
  components/cart/CartHeader.js
  components/cart/CartProduct.js
  components/cart/CartSidebar.js
  components/cart/EmptyCart.js
  components/order/OrderProductList.js
  pages/404.js
  pages/user/cart/index.js
  pages/user/order/index.js
  public/parabole.png
  public/parabole.svg
  public/parabole_pink.png
  public/parabole_pink.svg
Labels: Fix, Feat

#97 [Hotfix/SellerHeader] Import useEffect in SellerHeader
  components/seller/SellerHeader.js
Labels: !HOTFIX!

#87 [feature/events] 이벤트 상세 - 경품목록과 응모내역 확인, 이벤트 오류 수정, 셀러 헤더 링크 변경
  components/common/MainContent.js
  components/event/EventParticipant.js
  components/event/EventParticipantList.js
  components/seller/SellerHeader.js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
  utils/functions.js
Labels: Fix

#88 [feature/login] 로그인 구현 완료
  .gitignore
  apis/api-config.js
  apis/defaultApi.js
  components/common/CommerceHeader.js
  components/coupon/CouponList.js
  components/coupon/UserCouponList.js
  components/mypage/MyProfile.js
  components/seller/SellerHeader.js
  hooks/useGetToken.js
  pages/googlelogin.js
  pages/oauthkakao.js
  pages/user/signin.js
  pages/user/signout.js
  pages/user/signup.js
  pages/user/welcome/[id].js
  utils/functions.js
Labels: Feat

#101 [feature/upload] 상품과 이벤트 이미지 등록
  components/common/CommerceHeader.js
  components/common/Footer.js
  components/input/CloseButton.js
  components/order/SellerOrder.js
  components/product/ProductList.js
  components/seller/SellerHeader.js
  pages/404.js
  pages/seller/event/new.js
  pages/seller/main.js
  pages/seller/product/index.js
  pages/seller/product/new.js
  pages/user/signin.js
  pages/user/welcome/[id].js
  utils/constants/errors.js
  utils/constants/links.js
Labels: Feat

#103 [feature/event-scheduler] 셀러오피스에서 이벤트 등록시 기등록된 이벤트 조회하는 스케쥴러 구현
  components/Scheduler/scheduler.js
  components/event/ModalScheduler.js
  package-lock.json
  package.json
  pages/seller/event/new.js
  pages/seller/main.js
  utils/constants/errors.js
  utils/functions.js
Labels: Fix, Feat

#108 [Feature/orderMain] 주문 페이지 쿠폰 적용 및 컴포넌트 분리작업
  assets/no-photo.png
  assets/no-photo.svg
  components/input/CloseButton.js
  components/input/Input.js
  components/order/OrderCouponModal.js
  components/order/OrderDetail.js
  components/order/OrderDetailContent.js
  components/order/OrderDetailFooter.js
  components/order/OrderDetailHeader.js
  components/order/OrderProductList.js
  components/order/OrderSidebar.js
  components/order/OrdererSection.js
  components/order/Pay.js
  components/order/PayList.js
  pages/user/order/index.js
  utils/constants/images.js
Labels: Fix, Feat, Refactor

#115 [Feature/HeaderNFooter] 헤더 반응형 추가
  assets/icon-basket.svg
  assets/icon-gift.svg
  assets/icon-menu.svg
  components/common/CommerceHeader.js
  components/common/CommerceHeaderMenuModal.js
  components/common/CommerceLayout.js
  components/common/CustomSwiper.js
  components/input/SearchBar.js
  pages/product/index.js
  pages/signin.js
  utils/constants/icons.js
Labels: Feat

#116 HOTFIX: build할 때 생기는 문제들 해결
  components/input/SelectBox.js
  pages/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
  script/run_dev.sh
Labels: !HOTFIX!

#119 [feature/inputfix] 쿠폰 목록에 UI 수정
  components/common/CommerceHeader.js
  components/coupon/CouponList.js
  components/coupon/CouponListRadio.js
  components/coupon/UserCouponList.js
  components/coupon/UserSearchBar.js
  pages/seller/coupon/assign.js
  pages/seller/coupon/assignAf.js
  pages/seller/coupon/new.js
  pages/seller/event/new.js
  utils/constants/types.js
Labels: Feat, Design

#121 [feature/event winner] 이벤트 당첨자 리스트
  apis/api-config.js
  components/event/EventWinner.js
  components/event/EventWinnerList.js
  pages/seller/event/[id].js
Labels: Fix, Feat

#122 [Feature/cartAndOrder] 주문 장바구니 userId 제거
  components/cart/CartContent.js
  components/cart/CartContentDetail.js
  components/cart/CartHeader.js
  components/cart/CartProduct.js
  components/cart/EmptyCart.js
  components/coupon/CouponListRadio.js
  components/mypage/MyProfile.js
  components/mypage/UserOrderList.js
  components/order/OrderSidebar.js
  components/order/OrdererSection.js
  components/order/SellerOrderList.js
  components/seller/SellerHeader.js
  pages/404.js
  pages/product/[id].js
  pages/seller/main.js
  pages/seller/order/detail/index.js
  pages/seller/product/[id].js
  pages/seller/product/index.js
  pages/seller/product/list.js
  pages/seller/product/new.js
  pages/signin.js
  pages/user/cart/index.js
  pages/user/mypage/index.js
  pages/user/order/index.js
Labels: Fix, Feat

#123 [Feature/proeductDesc] 상품 최신순 정렬 안되던 오류 수정
  components/product/ProductList.js
  pages/index.js
  pages/product/index.js
  pages/store/[id].js
Labels: Feat

#120 [Hotfix] sh파일 수정
  script/run_dev.sh
Labels: !HOTFIX!

#118 [feature/auth-event] 인증 부분 수정
  pages/seller/event/list.js
  pages/seller/event/new.js
Labels: Feat

#124 [feature/backendhost] HOTFIX: 마켓 백엔드 서버에서 API GATEWAY서버로 호스트 변경함
  apis/api-config.js
Labels: !HOTFIX!

#126 [feature/product-coupon] 상품 화면에서 스토어 쿠폰 다운르도 기능구현
  components/coupon/CouponListModal.js
  pages/product/[id].js
Labels: Feat

#129 [feature/seller-office] 셀러오피스 화면 수정
  components/input/SortButton.js
  components/order/SellerOrder.js
  components/order/SellerOrderList.js
  pages/seller/event/list.js
  pages/seller/main.js
  pages/seller/order/detail/index.js
  pages/seller/product/list.js
  utils/constants/types.js
Labels: Feat, Design

#131 [hotfix/storeinfo] HOTFIX: import 경로 오류 수정
  components/product/ProductList.js
Labels: !HOTFIX!

#134 [feature/uifix] 로그인 회원가입 입력창 예외처리 / 쿠폰 입력창 & 노션 오류(잔수정)
  components/coupon/CouponList.js
  components/coupon/CouponListRadio.js
  components/coupon/UserSearchBar.js
  pages/seller/coupon/new.js
  pages/seller/event/new.js
  pages/signin.js
  pages/signup.js
  utils/constants/errors.js
Labels: Fix, Design

#136 [feature/fix/events] 셀러오피스 - 이벤트 목록 및 상세 오류 및 화면 수정
  components/event/Event.js
  components/event/EventParticipant.js
  components/event/EventParticipantList.js
  components/event/EventSampleModal.js
  components/event/EventStatusSummary.js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
Labels: Feat

#138 [hotfix/login-password] 로그인 비밀번호 유효성 검사 제거
  pages/signin.js
Labels: !HOTFIX!

#125 [feature/login-redirect] 소셜 로그인 리다이렉트 주소 배포도메인으로
  apis/api-config.js
  pages/signin.js
Labels: Fix, Feat

#137 [feature/sellerfix] 노션 오류 발견 페이지 <테마 3번 판매자 작업>
  apis/defaultApi.js
  pages/product/[id].js
  pages/seller/product/list.js
  pages/seller/product/new.js
  pages/signin.js
  pages/signup.js
  utils/constants/links.js
Labels: Fix, Design

#135 [Feature/extractCouponOrder] 주문 쿠폰적용 알고리즘 변경
  components/cart/CartContentDetail.js
  components/cart/CartProduct.js
  components/common/CommerceHeader.js
  components/common/CommerceHeaderMenuModal.js
  components/order/OrderCouponModal.js
  components/order/OrderDetail.js
  components/order/OrderDetailContent.js
  components/order/OrderDetailFooter.js
  components/order/OrderSidebar.js
  components/order/OrdererSection.js
  pages/signin.js
  pages/user/order/index.js
Labels: Fix

#105 [feature/design/event] 이벤트 응모화면 수정 중
  assets/no_event_banner_img.png
  assets/no_event_detail_img.png
  components/common/Timer.js
  components/event/EvenInfo.js
  components/event/EventParticipant.js
  components/event/EventPrizeContainer.js
  components/event/EventSampleModal.js
  pages/app.css
  pages/event/[id].js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
  utils/constants/images.js
Labels: Feat, Design

#142 [Feature/responsiveMypage] 마이페이지 반응형 수정
  components/coupon/CouponListModal.js
  components/coupon/UserCouponList.js
  components/mypage/EventApplyList.js
  components/mypage/MyProfile.js
  components/mypage/UserCoupon.js
  components/mypage/UserCouponList.js
  components/mypage/UserOrder.js
  components/mypage/UserOrderList.js
  components/store/StoreInfo.js
  pages/coupon/list.js
  pages/signin.js
  pages/user/mypage/index.js
  utils/constants/links.js
Labels: Feat

#146 [feature/so] 이벤트 등록 및 기타 오류 수정
  components/event/EventPrizeContainer.js
  pages/seller/event/new.js
  pages/seller/product/list.js
  utils/constants/types.js
Labels: Fix, Design

#139 [Feature/head] 메타태그, 오픈그래프 추가
  components/common/SiteHead.js
  pages/event/[id].js
  pages/event/index.js
  pages/product/[id].js
  pages/product/index.js
Labels: Feat

#148 [feature/eventdetail] 충돌 해결 원복
  pages/event/[id].js
  pages/seller/event/new.js
Labels: Feat

#147 [feature/productlist event fix] 텍스트 변경, 이미지 없을 때 처리 등
  apis/api-config.js
  components/event/EvenInfo.js
  components/event/EventPrizeContainer.js
  components/product/Product.js
  pages/product/[id].js
  pages/seller/product/list.js
  pages/seller/product/new.js
Labels: Fix, Feat

#149 [feature/eventWinnerPrize] 이벤트 응모 상품 당첨 내용
  components/mypage/EventApplyList.js
Labels: Fix

#140 [fix/errors] QA시 오류 발견 페이지 수정사항
  apis/api-config.js
  components/order/SellerOrder.js
  components/order/SellerOrderList.js
  pages/seller/coupon/list.js
  pages/seller/coupon/new.js
  pages/signin.js
  utils/constants/errors.js
Labels: Fix

#150 [Feature/eventdetails] 이벤트 응모 화면에서 응모 여부에 따라 버튼 disabled처리 안되는 오류 수정
  components/event/EventPrizeContainer.js
  components/event/EventStatusSummary.js
  components/mypage/EventApplyList.js
  pages/event/[id].js
Labels: Fix, Design

#145 [Feature/couponmodal] 상품상세페이지 반응형 추가
  components/coupon/StoreCouponListModal.js
  components/store/StoreInfo.js
  pages/product/[id].js
Labels: Fix, Feat

#151 [Fix: 이벤트 응모 내역 조회안되는 오류 수정]
  components/event/EventParticipant.js
  pages/seller/event/[id].js
Labels: Fix

#152 [Feature/mainFooter] 푸터 반응형추가, 이벤트 응모페이지 반응형 수정 및 오류 수정
  assets/icon-github.svg
  assets/icon-notion.svg
  components/common/Footer.js
  components/event/EvenInfo.js
  components/event/EventPrizeContainer.js
  components/mypage/EventApplyList.js
  pages/event/[id].js
  pages/user/order/index.js
  utils/constants/icons.js
Labels: Fix, Feat

#153 Fix: 푸터 왼쪽으로 치우쳐져있던 오류 수정
  components/common/Footer.js
Labels: Fix

#154 Fix: 메인페이지 파라볼래 문구를 더 파라볼래로 수정
  components/cart/CartContentDetail.js
  components/cart/CartContentFooter.js
  components/cart/CartProduct.js
  components/common/MainContent.js
  pages/index.js
Labels: Fix

#155 [hotfix/url] Frontend 주소 https to http
  apis/api-config.js
Labels: !HOTFIX!

#157 [Hotfix/event] 이벤트 오류 수정사항
  components/Scheduler/scheduler.js
  components/event/Event.js
  components/event/EventSampleModal.js
  pages/seller/event/new.js
Labels: Fix
