Repository Lotte-Feelmycode/the-parabole-fe, pull requests merged in 2022-10, with the labels that each got.

#11 [Feature/productList] 상품목록 백엔드에서 받아오도록 수정
  .babelrc.json
  apis/defaultApi.js
  components/common/SiteHead.js
  components/product/Product.js
  components/product/ProductList.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/index.js
  styles/Home.module.scss
  styles/globals.scss
Labels: Feat

#21 [Feature/productList] 상품 상세페이지 구현 및 판매자 페이지 구조 변경
  components/common/CommerceHeader.js
  components/product/Product.js
  components/product/ProductList.js
  components/seller/SellerHeader.js
  pages/product/[id].js
  pages/productDetail/[id].js
  pages/seller/main.js
Labels: Feat

#22 [Feature/component-template] Heading, Input, Button, Image Uploader 공통 컴포넌트 구현, 이벤트 등록 페이지 구현
  assets/imgUploadThumb.png
  components/input/Button.js
  components/input/Heading.js
  components/input/ImageUploader.js
  components/input/Input.js
  components/input/Radio.js
  package-lock.json
  pages/seller/event/posting.js
  utils/constants/errors.js
  utils/constants/images.js
Labels: Feat, Design

#26 [Feature/productList] 상품 목록 & 상품 상세페이지
  apis/api-config.js
  components/common/Pagination.js
  components/product/Product.js
  components/product/ProductList.js
  pages/product/[id].js
  utils/constants/themeColor.js
  utils/moneyUtil.js
Labels: Feat

#23 [feature/eventlist] event, eventlist component추가 및 목록 구현
  components/common/CommerceHeader.js
  components/event/Event.js
  components/event/EventList.js
  pages/event/index.js
  utils/functions.js
Labels: Feat

#25 [feature/orderlist] order, orderList 컴포넌트 추가 및 목록 조회
  components/order/Order.js
  components/order/SellerOrderList.js
  components/order/UserOrderList.js
  pages/seller/order/detail/[id].js
  pages/user/order/[id].js
Labels: Feat

#29 [Feature/productDetail] 상품 상세페이지 구현 및 input 아이템 테마적용 및 수정
  components/common/Pagination.js
  components/input/Button.js
  components/input/Input.js
  components/product/Product.js
  components/product/ProductList.js
  pages/index.js
  pages/product/[id].js
  pages/store/[id].js
  utils/constants/themeColor.js
Labels: Feat

#32 [feature/seller_product] ImageUploader에 있는 button 수정
  components/input/ImageUploader.js
  pages/seller/product/[id].js
Labels: Fix

#16 [feature/user] 로그인/회원가입 페이지
  components/common/CommerceHeader.js
  components/seller/SellerHeader.js
  pages/user/confirm/[id].js
  pages/user/signin.js
  pages/user/signup.js
Labels: Feat

#30 [feature/coupon] 쿠폰 조회/등록 컴포넌트 추가 및 화면 구현, defaultApi 함수 수정
  apis/defaultApi.js
  components/coupon/Coupon.js
  components/coupon/CouponList.js
  components/coupon/UserCoupon.js
  components/coupon/UserCouponList.js
  pages/coupon/list.js
  pages/seller/coupon/create.js
  pages/seller/coupon/list.js
Labels: Feat

#37 [Feature/seller-event] 셀러오피스 - 이벤트 등록, 삭제, 목록, 상세 조회 화면
  components/input/Radio.js
  components/seller/SellerHeader.js
  components/seller/SellerLayout.js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
  pages/seller/event/posting.js
  pages/seller/main.js
  utils/constants/types.js
Labels: Feat

#39 [Feature/productDetail] 상품 상세페이지 구현 추가 및 상품 목록 오류 수정
  apis/apis.js
  components/common/CommerceHeader.js
  components/input/Button.js
  components/input/ImageUploader.js
  components/input/Input.js
  components/product/ProductList.js
  components/seller/SellerHeader.js
  pages/product/[id].js
  pages/store/[id].js
Labels: Fix, Feat

#40 [feature/productDetail] 상품상세페이지 버튼 error 수정
  pages/product/[id].js
Labels: !HOTFIX!

#41 [Feature/seller-event] 빈값 유효성 검증 및 로직 추가
  pages/seller/event/[id].js
  pages/seller/event/list.js
Labels: Fix

#47 [feature/mypageMain] mypage 추가
  components/common/CommerceHeader.js
  pages/user/mypage/index.js
Labels: Feat

#44 [Feature/design/header] 헤더 변경 디자인 및 추가
  assets/cart-blue.svg
  assets/cart-transparent.svg
  assets/search-magnifiying-glass.svg
  components/common/CommerceHeader.js
  components/input/SearchBar.js
  fonts/AppleSDGothicNeoB.ttf
  fonts/AppleSDGothicNeoL.ttf
  fonts/AppleSDGothicNeoM.ttf
  fonts/AppleSDGothicNeoR.ttf
  pages/_app.js
  pages/app.css
  tailwind.config.js
  utils/constants/icons.js
Labels: Design

#58 [feature/seller_list] 목록을 가져오는 기능 구현
  components/coupon/CouponList.js
  components/event/Event.js
  components/event/EventList.js
  components/event/EventParticipant.js
  components/event/EventParticipantList.js
  components/order/SellerOrder.js
  components/order/UserOrder.js
  pages/seller/coupon/create.js
  pages/seller/coupon/list.js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/product/[id].js
  pages/seller/product/list.js
  pages/user/confirm/[id].js
  pages/user/signin.js
  pages/user/signup.js
  utils/functions.js
Labels: Feat, !HOTFIX!

#60 [feature/seller_list] 이벤트 목록 css 수정
  components/event/Event.js
  components/event/EventList.js
  pages/event/index.js
  pages/user/event/[id].js
  utils/constants/types.js
  utils/functions.js
Labels: Feat

#50 [feature/order] 주문/결제 페이지 구현
  components/event/EventParticipantList.js
  components/input/SelectBox.js
  components/order/Pay.js
  components/order/PayList.js
  components/order/Product.js
  components/order/ProductList.js
  components/order/SellerOrder.js
  components/order/SellerOrderList.js
  components/order/UserOrder.js
  components/order/UserOrderList.js
  components/product/SellerProductList.js
  pages/seller/event/list.js
  pages/seller/event/new.js
  pages/seller/product/list.js
  pages/user/order/index.js
  pages/user/order/list.js
  utils/constants/types.js
  utils/functions.js
Labels: Feat

#48 [feature/eventdetail] 이벤트 상세페이지 구현
  components/event/Coupon.js
  components/event/eventPrize.js
  pages/event/[id].js
  utils/functions.js
Labels: Fix, Feat

#62 [Feature/eventapplyinfo] 사용자 이벤트 상세 페이지 구현
  components/user/EventApply.js
  components/user/EventApplyList.js
  pages/user/mypage/index.js
  utils/constants/types.js
  utils/functions.js
Labels: Feat

#64 [Feature/events] 이벤트 등록 재고수정 버튼 추가 및 공통 함수 사용
  components/input/ImageUploader.js
  components/input/Radio.js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/seller/event/new.js
  utils/constants/errors.js
  utils/constants/types.js
  utils/functions.js
Labels: Fix, Feat

#65 [feature/design/commerce-main] 메인화면 디자인 및 레이아웃 수정
  assets/icon-heart-shopping-bag.svg
  assets/icon-online-shopping-2.svg
  assets/icon-online-shopping.svg
  assets/icon-open.svg
  assets/icon-percent.svg
  assets/icon-search.svg
  assets/icon-shop.svg
  assets/icon-truck.svg
  components/common/IconList.js
  components/common/MainContent.js
  components/product/Product.js
  components/product/ProductList.js
  pages/index.js
  utils/constants/icons.js
Labels: Feat, Design

#66 [feature/design/commerce-header] 헤더 반응형으로 수정 및 오류 수정
  assets/cart-black.svg
  components/common/CommerceHeader.js
  components/event/Event.js
  components/input/SearchBar.js
  utils/constants/icons.js
  utils/functions.js
Labels: Fix, Design

#68 [feature/product-page] 상품 목록 페이지 구현
  components/common/CommerceHeader.js
  components/common/CustomSwiper.js
  components/input/SearchBar.js
  components/product/ProductList.js
  package-lock.json
  package.json
  pages/product/index.js
Labels: Feat, Design

#69 [feature/design-css] 공통 Footer 디자인 수정, 셀러오피스 메인화면 구현
  assets/icon-check.svg
  assets/icon-list.svg
  assets/icon-post.svg
  components/common/Footer.js
  components/common/MainContent.js
  components/seller/SellerHeader.js
  pages/seller/main.js
  pages/user/mypage/index.js
  utils/constants/icons.js
Labels: Feat, Design

#70 [feature/coupon] 쿠폰 배정 페이지 동작 완성, 기존 회원관련 페이지 디자인 수정
  components/coupon/CouponList.js
  components/coupon/CouponListChk.js
  components/coupon/CouponListRadio.js
  components/coupon/UserSearchBar.js
  components/coupon/UserSearchResult.js
  pages/seller/coupon/assign.js
  pages/user/confirm/[id].js
  pages/user/signin.js
  pages/user/signup.js
  pages/user/welcome/[id].js
Labels: Feat

#67 [feature/page] 단건 주문 결제 및 헤더에서 모든 상품목록 반환할 수 있게 연결
  components/common/IconList.js
  components/order/PayList.js
  components/order/Product.js
  components/order/ProductList.js
  components/product/CartProduct.js
  components/product/OrderProductList.js
  components/product/Product.js
  pages/product/[id].js
  pages/product/index.js
  pages/seller/event/new.js
  pages/seller/order/detail/index.js
  pages/seller/product/[id].js
  pages/user/cart/index.js
  pages/user/mypage/index.js
  pages/user/order/index.js
  pages/user/order/list.js
  utils/functions.js
  utils/moneyUtil.js
Labels: Feat

#73 [Feature/orderPay] 주문 오류 수정
  components/order/UserOrder.js
  components/order/UserOrderList.js
  components/product/OrderProductList.js
  pages/user/order/index.js
Labels: Fix, Feat

#74 [feature/coupon] 쿠폰 등록시 시간은 00:00-23:59로 고정, 디자인 수정
  pages/seller/coupon/new.js
Labels: Feat, Design

#75 [feature/page] 주문정보를 가져오는 url수정
  components/order/UserOrderList.js
Labels: !HOTFIX!

#76 [feature/middle_presentation]Fix: 에러 및 스타일 수정
  components/coupon/CouponList.js
  components/order/SellerOrderList.js
  components/product/ProductList.js
  components/user/EventApplyList.js
  pages/index.js
  pages/seller/coupon/new.js
  pages/seller/event/[id].js
  pages/seller/product/index.js
  pages/seller/product/list.js
Labels: Design, !HOTFIX!

#80 [Feature/mypage_theme] 마이페이지 내부페이지 테마 일치화 및 일부 수정
  components/common/Pagination.js
  components/coupon/CouponList.js
  components/coupon/CouponListRadio.js
  components/coupon/UserCouponList.js
  components/event/Coupon.js
  components/event/Event.js
  components/event/EventParticipant.js
  components/input/Button.js
  components/input/Input.js
  components/mypage/EventApplyList.js
  components/mypage/MyProfile.js
  components/mypage/UserOrder.js
  components/mypage/UserOrderList.js
  components/order/Pay.js
  components/product/OrderProductList.js
  components/user/EventApply.js
  components/user/EventApplyList.js
  components/user/MyProfile.js
  pages/event/[id].js
  pages/product/[id].js
  pages/seller/event/[id].js
  pages/seller/event/list.js
  pages/user/cart/index.js
  pages/user/mypage/index.js
  pages/user/order/index.js
  utils/constants/themeColor.js
  utils/constants/types.js
  utils/functions.js
Labels: Fix

#78 [feature/events] 이벤트 등록 및 목록 조회 오류 수정
  assets/icon-warning-sign.svg
  components/input/Button.js
  components/input/Checkbox.js
  components/input/CloseButton.js
  components/input/Radio.js
  components/input/SelectBox.js
  hooks/useCheck.js
  pages/seller/event/list.js
  pages/seller/event/new.js
  utils/constants/icons.js
Labels: Fix, Feat, Design

#86 [Feature/main_list] 이벤트 목록 수정 & 상품 상세페이지 오류 수정 & 반응형 추가
  assets/coupon.svg
  components/common/CustomSwiper.js
  components/event/Coupon.js
  components/event/Event.js
  components/event/EventList.js
  components/event/eventPrize.js
  components/product/ProductList.js
  pages/event/[id].js
  pages/event/index.js
  pages/product/[id].js
  pages/product/index.js
  utils/constants/icons.js
Labels: Fix

#83 [feature/login] 일반로그인과 소셜로그인 구현
  apis/defaultApi.js
  components/common/CommerceHeader.js
  components/coupon/CouponList.js
  components/coupon/CouponListRadio.js
  components/coupon/UserCouponList.js
  components/coupon/UserSearchBar.js
  components/seller/SellerHeader.js
  components/user/SocialAfInfo.js
  pages/coupon/list.js
  pages/googlelogin.js
  pages/oauthkakao.js
  pages/seller/coupon/assign.js
  pages/seller/coupon/list.js
  pages/user/signin.js
  pages/user/signout.js
  pages/user/signup.js
  pages/user/welcome/[newname].js
  utils/functions.js
Labels: Feat
